version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  easy-docker-host:
    external: true  

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    depends_on:
      - cadvisor
      - pushgateway
    env_file:
      - stack.env
    networks:
      - easy-docker-host
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter    
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/data/docker-internal/containers|rootfs/data/docker-internal/overlay2|rootfs/run/docker/netns|rootfs/data/docker-internal/aufs)($$|/)"
    env_file:
      - stack.env      
    ports:
      - 9100
    networks:
      - easy-docker-host
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    env_file:
      - stack.env    
    ports:
      - 9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - easy-docker-host
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    privileged: true
    env_file:
      - stack.env
    devices:
      - /dev/kmsg:/dev/kmsg          
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /data/docker-internal/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /cgroup:/cgroup:ro
    ports:
      - 8080
    networks:
      - easy-docker-host
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    env_file:
      - stack.env
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - easy-docker-host
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway  
    env_file:
      - stack.env      
    restart: always
    ports:
      - 9091
    networks:
      - easy-docker-host
